### ISSUE TITLE
Feature-Request: Get CallerID from Tellows

### ISSUE THREAD

**Issue by moarph** [jacotec/FreePBX-Superfecta-Tellows#2]
Right not it detects if the caller is a spam caller or not (after I baught the API key). Well first of all thank you so much for your great work. A great feature would be to get the CallerID (Caller Name) from Tellows as well since this seems to be a bit better than the curret soltuions for Germany (dastelefonbuch.de, DeteMedien.de and so on)

**Comment by jacotec** [comment]
I don't see a way that the Tellows live API delivers the caller name. As far as I see this is a feature of the score list you can download for offline use. Or do you have any more information how the live API can deliver the caller name?

Also, in the scorelist API, the caller names are entered by the community and this is no official information. Example:

```
    {
        "number": "08989679862",
        "score": 8,
        "complains": 55,
        "country": 49,
        "prefix": 89,
        "searches": 23049,
        "callertype": "Meinungsforschung",
        "callername": "Wein Umfrage",
        "callertypeid": 6
    },

```

**Comment by moarph** [comment]
Well one could move the Tellows module under Telefonbuch and DeTeMedien. My opinion is: SOME caller name is better than no caller name at all. In tghis special case I'd know that a "Wein Umfrage"-caller would not get my attention during an importannt task were as a number in the Munich-area could be a potentional customer.

**Comment by moarph** [comment]
`                } else {
                   $result = json_decode($json,true);
                   $value = $result['tellows']['score'];
                   $comments = $result['tellows']['comments'];
                   $searches = $result['tellows']['searches'];

                   if (isset($result['tellows']['callerNames']['caller'][0])) {
                           $caller_id = $result['tellows']['callerNames']['caller'][0];
                   }

                   if (isset($result['tellows']['numberDetails']['name'])) {
                           $caller_id = $result['tellows']['numberDetails']['name'];
                   }

                   if (is_numeric($value)) {
                           $this->DebugPrint(_('Found')." score ".$value." (".$run_param['SPAM_Threshold'].") with ".$comments." (".$run_param['COMMENTS_Threshold'].") comments and ".$searches." (".$run_param['SEARCHES_Threshold'].") searches");

                           $score = $value;
                           if ($score >= $run_param['SPAM_Threshold'] AND $comments >= $run_param['COMMENTS_Threshold'] AND $searches >= $run_param['SEARCHES_Threshold']) {
                                   $this->spam = true;
                                   $this->DebugPrint(" "._("determined to be SPAM"));
                           } else {
                                   $this->DebugPrint(_("Not a SPAM caller"));
                           }
                   }
                   if (isset($caller_id)) {
                           return($caller_id);
                   }
                }`
I added this to your code - works fine with my tests. Maybe you can include this?

**Comment by jacotec** [comment]
@moarph Personally I don't see a value in having a random community entered name / description in the caller name field. But feel free to fork my script to use it in a way it'll fit your needs ;-)
